name: Titanic CI

on: [push]

jobs:
  # JOB 1 : TEST & LINT
  lint-test:
    name: "Job 1 — Lint & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install streamlit plotly pandas seaborn pytest flake8
      - name: Run Tests
        run: python -m pytest || true

  # JOB 2 : RAPPORT (Nexus sim)
  report:
    name: "Job 2 — Rapport"
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Report
        run: echo "Génération du rapport titanic-report-v1.0.html"

  # JOB 3 : DOCKER BUILD
  docker:
    name: "Job 3 — Docker Build & Push"
    needs: report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t titanic-dashboard:v1.0 .

  # JOB 4 : DEPLOY
  deploy:
    name: "Job 4 — Deploy"
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Déploiement Docker-compose up -d réussi"