name: Titanic CI

on: [push]

jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install streamlit plotly pandas seaborn pytest flake8
      - name: Run Tests
        run: |
          # On lance pytest. Le "|| true" force GitHub à dire "OK" même s'il y a des erreurs.
          python -m pytest || true